- hosts: all
  connection: local
  gather_facts: no
  vars:
    classs_list:
      - mhco
      - ceo
      - mjo
      -
  tasks:
    - name: Dump Class List
      debug:
        msg: "{{ item }}"
      with_items: "{{ classs_list }}"
