- hosts: all
  connection: local
  gather_facts: no
  vars:
    classs_size: 1
      -
  tasks:
    - name: Dump Class List
      debug:
        msg: "{{ item }}"
      with_sequence: count={{ class_size }} 
